export const RETRIEVE_ORDER_LIST = 'RETRIEVE_ORDER_LIST';
export const RETRIEVE_ORDER_DETAILS = 'RETRIEVE_ORDER_DETAILS';
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';

export const RETRIEVE_PRODUCT_LIST = 'RETRIEVE_PRODUCT_LIST';
